### ISSUE TITLE
Javascript Obfuscation using closure-compiler

### ISSUE THREAD

**Issue by rafasashi** [devize/closure-compiler#5]
Im using it and it works perfectly thanks!
Is it possible to obfuscate the code with closure-compiler?

**Comment by Breuls** [comment]
Hi @rafasashi, you can look up the details of the Closure Compiler at Google's website: https://developers.google.com/closure/compiler/

My package is just a wrapper around it. :)

**Comment by rafasashi** [comment]
Hi @Breuls thanks for the info. Once again well done!

**Comment by Breuls** [comment]
You're welcome. :)
